name: Release Gradle Publish

on:
  release:
    types: [ created ]

env:
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEYID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
  
    - name: Sanity Check
      run: |
        ./gradlew \
          sdk:lint sdk-compose:lint \
          sdk:test sdk-compose:test

    - name: Publish to Maven Local
      run: |
        ./gradlew \
          sdk:publishToMavenLocal sdk-compose:publishToMavenLocal

    - name: Publish to Maven
      run: |
        ./gradlew \
          sdk:publish sdk-compose:publish